name: build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
      - run: ./gradlew --no-daemon :app:assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./app/build/outputs/apk/debug/*.apk
          retention-days: 3
